const Images = {
    amazon: require('./amazon.png'),
    boy: require('./boy.png'),
    computer: require('./computer.png'),
    cute: require('./cute.png'),
    facebook: require('./facebook.png'),
    fiverr: require('./fiverr.png'),
    github: require('./github.png'),
    glasses: require('./glasses.png'),
    humble: require('./humble.png'),
    instagram: require('./instagram.png'),
    like: require('./like.png'),
    linkedin: require('./linkedin.png'),
    loveheartsg: require('./loveheartsg.png'),
    porttfolio1: require('./Portfolio_1.jpg'),
    porttfolio2: require('./Portfolio_2.png'),
    porttfolio3: require('./Portfolio_3.png'),
    porttfolio4: require('./Portfolio_4.png'),
    porttfolio5: require('./Portfolio_5.png'),
    porttfolio6: require('./Portfolio_6.png'),
    wave: require('./wave.png'),
    vectorBlue: require('./Vector1.png'),
    vectorYellow: require('./Vector2.png'),
    heartemoji: require('./heartemoji.png'),
    wink: require('./wink.png'),
    person1: require('./profile1.jpg'),
    person2: require('./profile2.jpg'),
    person3: require('./profile3.jpg'),
    person4: require('./profile4.jpg'),
}
export default Images
